services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'